name: Mon premier workflow
env:
  VARIABLE_NAME: value
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: display variable
        run: echo ${{ env.VARIABLE_NAME }}
      - name: display MA_VARIABLE
        run: echo ${{ env.MA_VARIABLE }}
      - name: Use a Secret
        env:
          SUPER_SECRET: ${{ secrets.SECRET_NAME }}
        run: echo $SUPER_SECRET
