name: Mon premier workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Exécuter une action
        uses: actions/hello-world-docker-action@v1
  macos:
    runs-on: macos-latest
    steps:
      - name: Add new directory
        run: mkdir new_directory
      - name: List files
        run: ls -al
  windows:
    runs-on: windows-latest
    steps:
      - name: List files
        run: ls
