name: Mon premier workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Exécuter une action
        uses: actions/hello-world-docker-action@v1
  new-directory:
    runs-on: alpine-latest
    steps:
      - name: Add new directory
        run: mkdir new_directory
      - name: List files
        run: ls -al
