name: Mon premier workflow
env:
  VARIABLE_NAME: value
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: display variable
        run: echo ${{ env.VARIABLE_NAME }}
